---
- name: Install Nginx
  apt:
    name: nginx-light
    state: present

- name: Copy new config
  copy:
    src: default
    dest: /etc/nginx/sites-available/

- name: Fetch site content
  git:
    repo: "{{ freedomnet_content }}"
    dest: "{{ doc_root }}"
    version: "{{ content_version }}"
  notify:
    - Restart nginx
