---
- name: Restart dhcpcd
  service:
    name: dhcpcd
    state: restarted

- name: Restart hostapd
  service:
    name: hostapd
    state: restarted

- name: Restart dnsmasq
  service:
    name: dnsmasq
    state: restarted